version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    command: ["sh", "-c", "sleep 10 && python -c 'import asyncio; from app.db.session import create_tables; asyncio.run(create_tables())' && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    environment:
      - DB_POSTGRES_HOST=db
      - DB_POSTGRES_PORT=5432

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: Brouser77
      POSTGRES_DB: system_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d system_data"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5434:5432"

volumes:
  postgres_data:
